features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost/~nico/bb8/themes/bootstrap/favicon.ico'
  use_default: 0
logo:
  path: ''
  url: ''
  use_default: true
schema: 8000
