charts_default_settings:
  library: google
  type: line
  title: MyChart
  colors:
    - '#2f7ed8'
    - '#0d233a'
    - '#8bbc21'
    - '#910000'
    - '#1aadce'
    - '#492970'
    - '#f28f43'
    - '#77a1e5'
    - '#c42525'
    - '#a6c96a'
  title_position: out
  tooltips: ''
  data_labels: ''
  legend_position: right
  background: ''
  three_dimensional: 0
  polar: 0
  width: ''
  width_units: '%'
  height: ''
  height_units: px
  xaxis_title: xaxis
  xaxis_labels_rotation: '90'
  yaxis_title: yaxis
  yaxis_min: ''
  yaxis_max: ''
  yaxis_prefix: ''
  yaxis_suffix: ''
  yaxis_decimal_count: ''
  yaxis_labels_rotation: '0'
