palette:
  top: '#b7c205'
  bottom: '#d4f50f'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071B3'
logo: 'public://color/bartik-12f43107/logo.svg'
stylesheets:
  - 'public://color/bartik-12f43107/colors.css'
files:
  - 'public://color/bartik-12f43107/logo.svg'
  - 'public://color/bartik-12f43107/colors.css'
