module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  bb: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  date_popup: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  formateur: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  node: 0
  offres: 0
  options: 0
  page_cache: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_length: 0
  path: 0
  pia: 0
  quickedit: 0
  rdf: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_block_area: 0
  views_current_path: 0
  views_data_export: 0
  views_ui: 0
  xls_serialization: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bbtheme: 0
  bootstrap: 0
  pia: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
