grants:
  view: 1
  edit: 1
  delete: 1
priority: 1
preserve: 1
_core:
  default_config_hash: Zno4MMkbreZeJZgnY0DXCPksXkuYye3MyIFlVuh-xLc
article:
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_cons:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_admi:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
page:
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  anonymous:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_cons:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_admi:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
page_riche:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_cons:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  d_admi:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
role_alias:
  anonymous:
    allow: '1'
    alias: 'Utilisateur anonyme'
    weight: '0'
    name: 'Utilisateur anonyme'
  authenticated:
    allow: '1'
    alias: 'Utilisateur authentifié'
    weight: '0'
    name: 'Utilisateur authentifié'
  administrator:
    allow: '1'
    alias: Administrateur
    weight: '0'
    name: Administrateur
  d_cons:
    allow: '1'
    alias: D_cons
    weight: '0'
    name: D_cons
  d_admi:
    allow: '1'
    alias: D_admi
    weight: '0'
    name: D_admi
role_map:
  anonymous: 1
  authenticated: 2
  administrator: 3
  d_cons: 4
  d_admi: 5
langcode: fr
allowed_types:
  article: 1
  page: 1
  page_partage: 0
  page_riche: 1
page_partage:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: '1'
    grant_update: '1'
    grant_delete: '1'
  d_cons:
    grant_view: '1'
    grant_update: '1'
    grant_delete: '1'
  d_admi:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: '1'
    grant_update: '1'
    grant_delete: '1'
