id: general
label: General
password_reset: 730
langcode: fr
policy_constraints:
  -
    id: character_types
    character_types: 2
  -
    id: password_length
    character_length: 8
    character_operation: minimum
roles:
  authenticated: authenticated
