favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://daforbb.scola.ac-paris.fr/bb8dev/web/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  pia: 8000
