<?php

/**
 * @file
 * Contains pia.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pia_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pia module.
    case 'help.page.pia':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gestion des pias') . '</p>';
      return $output;

    default:
  }
}

function pia_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $form['co_resp']['#type'] = 'hidden';
  }
}

function pia_preprocess_block(&$variables) {
  // dpm('lmm');
}

/**
 * Implements hook_theme().
 */
function pia_theme() {
  $vars = [
    'library' => '',
    'categories' => '',
    'seriesData' => '',
    'options' => '',
  ];
  return [
    'pia' => array(
      'template' => 'pia-layout',
      'render element' => 'form',
    ),
  ];
}
