<?php

use Drupal\file\FileInterface;

/**
 * Implements hook_file_download().
 *
 * Control the access to file download
 */
function bb_file_download($uri) {
  if (\Drupal::currentUser()->isAnonymous()) {
    return -1;
  } else {
  return 1;
  }
}

/**
 * Implements hook_views_api().
 */
function bb_views_api() {
  return array(
    'api' => 3,
    //'path' => drupal_get_path('module', 'expose') . '/includes/views',
    'path' => '.',
  );
}

function bb_theme($existing, $type, $theme, $path) {
  return array(
    'modal' => array(
      'template' => 'modal-layout',    // see templates/modal-layout.html.twig
      'render element' => 'form',
    ),
    'moduleng' => array(
      'template' => 'moduleng-layout', // see templates/moduleng-layout.html.twig
      'render element' => 'html',
    ),
  );
}
