<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function pia_preprocess_views_view_list__bb_pia__page_2(&$variables) {
    $str = "";
    $variables['mystring'] = $str;
}
