<?php

/**
 * Implements hook_views_api().
 */
function bb_views_api()
{
  return array(
    'api' => 3,
    //'path' => drupal_get_path('module', 'expose') . '/includes/views',
    'path' => '.',
                            );
}
function bb_theme($existing, $type, $theme, $path) {

  return array(
    'modal' => array(
      // see templates/modal-layout.html.twig
      'template' => 'modal-layout',
    ),
    'moduleng' => array(
      // see templates/moduleng-layout.html.twig
      'template' => 'moduleng-layout',
    ),
  );

}


\Drupal::state()->set('ico_attente',    '<i class="fa fa-pause" title="En attente : ne pas préparer les convocations pour le moment"></i>');
\Drupal::state()->set('ico_alert',      '<i class="fa fa-flag fa-lg red" title="Alerte à l\'attention du service administratif">&nbsp;</i>');
\Drupal::state()->set('ico_sent',       '<i class="fa fa-envelope green" title="La convocation pour cette session a été envoyée"></i>' );
\Drupal::state()->set('ico_notAttente', '<i class="fa fa-play-circle fa-lg blue" title="Demande de préparation des convocations"></i>');

