<?php

/**
 * Implements hook_views_api().
 */
function bb_views_api()
{
  return array(
    'api' => 3,
    //'path' => drupal_get_path('module', 'expose') . '/includes/views',
    'path' => '.',
                            );
}
function bb_theme($existing, $type, $theme, $path) {

  return array(
    'session' => array(
      'template' => 'session-form',
      //'variables' => array('texte' => 'coucou')
      // 'variables' => $existing
      'render element' => 'form',

    ),
  );

}

