<?php

/**
 * Implements hook_views_api().
 */
function bb_views_api()
{
  return array(
    'api' => 3,
    //'path' => drupal_get_path('module', 'expose') . '/includes/views',
    'path' => '.',
                            );
}
function bb_theme($existing, $type, $theme, $path) {

  return array(
    'moduleng' => array(
      // see templates/moduleng-layout.html.twig
      'template' => 'moduleng-layout',
    ),
    'module' => array(
      'template' => 'module-form',
      'render element' => 'form',
    ),
    'session' => array(
      // see templates/session-form.html.twig 
      'template' => 'session-form',
      'render element' => 'form',
    ),
  );

}

